name: Build Devel

on:
  workflow_dispatch:
  push:
    branches: [ "devel" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup roswell
      uses: 40ants/setup-lisp@v2
      with:
        asdf-system: cl-info

    - name: setup haskell
      uses: haskell/actions/setup@v2
      with:
        ghc-version: '9.6.1'
        cabal-version: '3.10.1.0'

    - name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
      uses: actions/cache@v3
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal', '**/cabal.project', '**/cabal.project.freeze') }}
        restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-

    - name: Update Package list
      run: make dep-update

    - name: Build & Generate
      run: make gh

    - name: Setup Pages
      uses: actions/configure-pages@v2

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: "./docs"
